version: '3'

networks:
  backend:
    driver: bridge

services:
  postgres:
    image: postgres
    volumes:
      - ./psql-data:/var/lib/postgresql/data
    networks:
      - backend

  api:
    build:
      context: .
    networks:
      - backend
    ports:
      - "127.0.0.1:8080:5000"
    depends_on:
      - postgres

  web:
    build:
      context: ./web
    ports:
      - "127.0.0.1:5000:5000"
