version: '3'

volumes:
  fortune_teller: {}

networks:
  nw:
    driver: bridge

services:
  postgres:
    image: postgres
    volumes:
      - fortune_teller:/var/lib/postgresql/data
    networks:
      - nw
  fortune_teller:
    build: .
    networks:
      - nw
    ports:
      - 5000:5000
    depends_on:
      - postgres
