apiVersion: apps/v1
kind: Deployment
metadata:
  name: ft
  labels:
    name: ft
spec:
  replicas: 3
  selector:
    matchLabels:
      name: ft
  template:
    metadata:
      name: ft
      labels:
        name: ft
    spec:
      containers:
        - name: ft
          image: FHA-FB5/FortuneTeller:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: 128Mi
            limits:
              memory: 256Mi
          env:
            - name: ENV
              value: "{{.TOKEN}}"
